### ISSUE TITLE
Open bufferize in a vertical split?

### ISSUE THREAD

**Issue by vzytoi** [AndrewRadev/bufferize.vim#10]
Hey, firstly I really love your plugin.
Is there any way to open the buffer vertically?
Thanks (:

**Comment by AndrewRadev** [comment]
> Hey, firstly I really love your plugin.

Thanks, I appreciate it :)

You could use the setting `g:bufferize_command` to `vertical new` for a vertical split on the left or `botright vertical new` for a vertical split on the right. Would this work for you? You can read more here: https://github.com/AndrewRadev/bufferize.vim/blob/ec0ecb382443db0f9553f3bd090b58e782e0258d/doc/bufferize.txt#L103-L111

**Comment by vzytoi** [comment]
I wanted to have a different command to show the buffer below and vertically, I tried this but it don't seem to work :
```
function M.splitExecute()

    vim.api.nvim_command("let g:bufferize_command='rightbelow'|Bufferize !" .. M.command())

end

function M.verticalExecute()

    vim.api.nvim_command("let g:bufferize_command='vertical'|Bufferize !" .. M.command())

end

```

**Comment by AndrewRadev** [comment]
That's a good point, it would be nice to allow invoking it differently -- I poked around in the documentation and figured out how to do it, so now you should be able to execute `vertical Bufferize <command>`

**Comment by vzytoi** [comment]
Really nice, thank you!
