### ISSUE TITLE
Issue with g command

### ISSUE THREAD

**Issue by fvictorio** [AndrewRadev/bufferize.vim#3]
I tried doing this:

```
Bufferize g/\v(describe|it)\(/
```

and I got this error:

```
Error detected while processing function bufferize#Run:
line   32:
E492: Not an editor command: it)\(/
```

I guess it has something to do with the `\(`, since running something like `Bufferize g/\vdescribe/` works fine.

**Comment by AndrewRadev** [comment]
Ah, a problem with escaping the `|` character, and a follow-up issue with needing to escape `\` as well. I pushed a fix, could you try it again?

**Comment by fvictorio** [comment]
It worked, thanks!
