### ISSUE TITLE
Document the :RunCommand integration point

### ISSUE THREAD

**Issue by mgedmin** [AndrewRadev/bufferize.vim#4]
I've noticed [these lines](https://github.com/AndrewRadev/bufferize.vim/blob/eb92f027c25dc907d48bfaea035391769899da83/autoload/bufferize.vim#L44-L46) in the plugin

```vim
  if exists(':RunCommand')
    exe 'RunCommand silent Bufferize '.a:cmd
  endif
```

and I would like to understand what they're meant to do.

What plugin defines a `:RunCommand`?  Should this be mentioned somewhere in the documentation?

**Comment by AndrewRadev** [comment]
Ah. This is something that used to be there when the plugin was just a part of my vimrc, I think :). I'm not sure if I deliberately left it there or just forgot. 

The `:RunCommand` command is defined in my vimrc: https://github.com/AndrewRadev/Vimfiles/blob/4ba488a82a4a6ca16dc1aaff8693cf44b4e1d932/startup/commands.vim#L89-L91

It defines a command called `:Run` for the current filetype that is a filetype-specific way of executing the file. In ruby, for instance: https://github.com/AndrewRadev/Vimfiles/blob/4ba488a82a4a6ca16dc1aaff8693cf44b4e1d932/ftplugin/ruby/commands.vim#L10

I also have a short mapping that just runs the `:Run` command: https://github.com/AndrewRadev/Vimfiles/blob/4ba488a82a4a6ca16dc1aaff8693cf44b4e1d932/startup/mappings.vim#L151-L152

> What plugin defines a :RunCommand? Should this be mentioned somewhere in the documentation?

More like I should probably remove it from the plugin :). With it, in my vimrc, pressing `!` in normal mode would re-run the command that generated it, but I think I can implement this from outside the plugin without polluting it with config-specific stuff.

**Comment by mgedmin** [comment]
Oh, neat!  Thank your for explaining.

(Yeah, maybe it shouldn't be a part of the plugin -- but maybe remembering the command in a buffer-local variable would be helpful for this kind of re-run-please automation.)

**Comment by AndrewRadev** [comment]
It's a good idea to just keep the command, I agree. This should do it, I think: https://github.com/AndrewRadev/bufferize.vim/commit/023ee69c9cd3fe97d537e8baa7b82a88d20cf155
